on: [workflow_dispatch]
name: Update git submodules

jobs:
  build:
    name: Update git submodules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/main
          submodules: true
      - run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - run: |
          git config --global user.email "doc-bot@example.com"
          git config --global user.name "DocBot"
          git commit -am "Auto update the submodules" && git push || echo "Nothing to do"

